### ISSUE TITLE
Copy .funcignore to dist folder

### ISSUE THREAD

**Issue by jvpelt** [ziacik/nx-tools#32]
Any chance you could add the ability to copy the .funcignore from the source to the dist folder. I tried adding it to the assets but it seems like files without extension are not copied with the esbuild target.

**Comment by ziacik-resco** [comment]
@jvpelt Since the dist folder is built to contain only the files that are meant for publish already, is there any particular reason to have .funcignore there too?

**Comment by ziacik** [comment]
@jvpelt Since the dist folder is built to contain only the files that are meant for publish already, is there any particular reason to have .funcignore there too?

**Comment by ziacik** [comment]
@jvpelt Anyway, I was able to add .funcignore to the assets and it appeared in the dist:

![image](https://github.com/ziacik/nx-tools/assets/4528506/564a8257-7085-4f9f-bc24-c216fdc12e9c)

`$ ls -lah dist/apps/ai-api/`

![image](https://github.com/ziacik/nx-tools/assets/4528506/954a951e-0d16-434a-a49a-1f465ffda82f)

It it possible that you just didn't have the hidden files shown when inspecting the dist?
If i was to implement this, I would probably just add it to the assets in generator...

**Comment by jvpelt** [comment]
> @jvpelt Since the dist folder is built to contain only the files that are meant for publish already, is there any particular reason to have .funcignore there too?

Without this file in the dist folder all packages are uploaded. I've got some libs which have dependencies to frontend packages which I wanted to manually exclude.

**Comment by jvpelt** [comment]
> @jvpelt Anyway, I was able to add .funcignore to the assets and it appeared in the dist:
> 
> ![image](https://private-user-images.githubusercontent.com/4528506/329868506-564a8257-7085-4f9f-bc24-c216fdc12e9c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzOTQxMjgsIm5iZiI6MTcxNjM5MzgyOCwicGF0aCI6Ii80NTI4NTA2LzMyOTg2ODUwNi01NjRhODI1Ny03MDg1LTRmOWYtYmMyNC1jMjE2ZmRjMTJlOWMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjJUMTYwMzQ4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzI4ODhkNjg1YmU2NTgyNTg4MTY5OGU4M2U2MzZkMTI3MTViNzI4ZmE0ZWNiZTBkMmU3ZDEzZTI1NmQxYTliMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Z9XDTUCqpGDmte6Woo2QgmNim3rJyontZv6Fd36tMY8)
> 
> `$ npx nx build ai-api && ls -lah dist/apps/ai-api/`
> 
> ![image](https://private-user-images.githubusercontent.com/4528506/329868543-954a951e-0d16-434a-a49a-1f465ffda82f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzOTQxMjgsIm5iZiI6MTcxNjM5MzgyOCwicGF0aCI6Ii80NTI4NTA2LzMyOTg2ODU0My05NTRhOTUxZS0wZDE2LTQzNGEtYTQ5YS0xZjQ2NWZmZGE4MmYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjJUMTYwMzQ4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTdiYmUxNzIxZjczMWVjM2RmYjkwYTU3ODgzNDFhNjM0YjkxYzBiYzViMmYzMjNmNWM5NGNhYjc2NzQ1YTNlYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.sSPlOBxHOMpjFjPBNJW0UStRXyNi3PUn2J-lvudgJp4)
> 
> Is it possible that you just didn't have the hidden files shown when inspecting the dist? If i was to implement this, I would probably just add it to the assets in generator...

my bad... not sure what I missed at first but it seems to work now.
